-- ============================================
-- SEED: Afirmaciones REALES de Manifiesta con Lau (96 afirmaciones, 8 categorias)
-- Fuente: Manifiesta_Datos_Glide.xlsx
-- ============================================

insert into public.affirmations (category, text) values
('Amor', 'Soy digno(a) de recibir y dar amor en abundancia.'),
('Amor', 'Mi corazón está abierto al amor verdadero y sincero.'),
('Amor', 'Amo y acepto quién soy completamente.'),
('Amor', 'Atraigo relaciones llenas de respeto y cariño.'),
('Amor', 'Estoy rodeado(a) de amor y alegría cada día.'),
('Amor', 'Merezco un amor que me haga sentir en casa.'),
('Amor', 'Cada relación que vivo me enseña a amarme mejor.'),
('Amor', 'Mi corazón sana a su propio ritmo y eso está bien.'),
('Amor', 'Doy y recibo amor sin miedo ni condiciones.'),
('Amor', 'Soy una fuente de amor genuino para mí y para los demás.'),
('Amor', 'Elijo rodearme de vínculos que me sumen, no que me resten.'),
('Amor', 'El amor que busco ya vive dentro de mí.'),
('Felicidad', 'Hoy elijo ser feliz y disfrutar del presente.'),
('Felicidad', 'La felicidad es mi derecho natural.'),
('Felicidad', 'Encuentro belleza y alegría en las pequeñas cosas de la vida.'),
('Felicidad', 'Mi vida está llena de momentos mágicos y positivos.'),
('Felicidad', 'Cada día me vuelvo más feliz y más pleno(a).'),
('Felicidad', 'Mi alegría no depende de circunstancias externas.'),
('Felicidad', 'Celebro mis pequeños logros con la misma fuerza que los grandes.'),
('Felicidad', 'Elijo ver lo bueno, incluso en los días difíciles.'),
('Felicidad', 'Soy capaz de crear felicidad con lo que ya tengo.'),
('Felicidad', 'Mi sonrisa es un acto de poder personal.'),
('Felicidad', 'Permito que la alegría entre en cada rincón de mi vida.'),
('Felicidad', 'Hoy decido disfrutar el camino, no solo la meta.'),
('Abundancia y Prosperidad', 'Estoy en armonía con la abundancia del universo.'),
('Abundancia y Prosperidad', 'Soy un imán para la abundancia y la prosperidad.'),
('Abundancia y Prosperidad', 'Estoy abierto(a) a recibir bendiciones ilimitadas.'),
('Abundancia y Prosperidad', 'Mis pensamientos están alineados con la energía de la abundancia.'),
('Abundancia y Prosperidad', 'Mi vida está llena de posibilidades infinitas.'),
('Abundancia y Prosperidad', 'Pienso en grande porque el universo piensa en grande conmigo.'),
('Abundancia y Prosperidad', 'Cada puerta que se cierra abre una mejor.'),
('Abundancia y Prosperidad', 'Mi abundancia no le quita nada a nadie, hay de sobra para todos.'),
('Abundancia y Prosperidad', 'Confío en que siempre voy a tener lo que necesito.'),
('Abundancia y Prosperidad', 'La prosperidad es mi estado natural.'),
('Abundancia y Prosperidad', 'Veo oportunidades donde antes veía obstáculos.'),
('Abundancia y Prosperidad', 'Mi vida se expande cada día un poco más.'),
('Abundancia Financiera', 'El dinero llega a mí fácilmente y sin esfuerzo.'),
('Abundancia Financiera', 'Mis ingresos están aumentando constantemente.'),
('Abundancia Financiera', 'Estoy rodeado(a) de oportunidades financieras ilimitadas.'),
('Abundancia Financiera', 'El dinero es un recurso positivo que fluye libremente hacia mí.'),
('Abundancia Financiera', 'Tengo el poder de crear una vida financiera estable y abundante.'),
('Abundancia Financiera', 'Tengo una relación sana y en paz con el dinero.'),
('Abundancia Financiera', 'Cada gasto que hago vuelve multiplicado.'),
('Abundancia Financiera', 'Soy capaz de generar ingresos de múltiples formas.'),
('Abundancia Financiera', 'Mi valor no se mide por mi cuenta bancaria, pero mi cuenta bancaria también crece.'),
('Abundancia Financiera', 'Tomo decisiones financieras desde la calma, no desde el miedo.'),
('Abundancia Financiera', 'El dinero es energía y fluye libremente en mi vida.'),
('Abundancia Financiera', 'Merezco ser recompensada generosamente por mi trabajo.'),
('Parejas y Relaciones', 'Atraigo a la pareja perfecta para mi crecimiento y felicidad.'),
('Parejas y Relaciones', 'Mi relación está llena de amor, respeto y comunicación.'),
('Parejas y Relaciones', 'Estoy listo(a) para compartir mi vida con alguien especial.'),
('Parejas y Relaciones', 'Mi energía atrae relaciones positivas y significativas.'),
('Parejas y Relaciones', 'El amor verdadero fluye hacia mí y me envuelve.'),
('Parejas y Relaciones', 'Construyo vínculos desde la seguridad, no desde la necesidad.'),
('Parejas y Relaciones', 'Sé reconocer cuándo una relación me hace bien.'),
('Parejas y Relaciones', 'Comunico lo que siento con claridad y respeto.'),
('Parejas y Relaciones', 'Atraigo personas que celebran quien soy.'),
('Parejas y Relaciones', 'Mi relación ideal empieza por cómo me trato a mí misma.'),
('Parejas y Relaciones', 'Confío en el momento justo para cada vínculo.'),
('Parejas y Relaciones', 'Merezco reciprocidad en todo lo que doy.'),
('Negocios y Clientes', 'Atraigo clientes ideales que valoran lo que ofrezco.'),
('Negocios y Clientes', 'Mi negocio crece de manera constante y exitosa.'),
('Negocios y Clientes', 'Los clientes adecuados encuentran mi negocio fácilmente.'),
('Negocios y Clientes', 'Confío en mis habilidades para crear un negocio exitoso.'),
('Negocios y Clientes', 'Mi trabajo impacta positivamente a quienes lo necesitan.'),
('Negocios y Clientes', 'Mi trabajo es valioso y se nota.'),
('Negocios y Clientes', 'Sé pedir lo que merezco por lo que ofrezco.'),
('Negocios y Clientes', 'Cada ''no'' me acerca a mi próximo ''sí''.'),
('Negocios y Clientes', 'Mi negocio refleja quién soy cuando estoy en mi mejor versión.'),
('Negocios y Clientes', 'Soy reconocida por la calidad de lo que hago.'),
('Negocios y Clientes', 'Las oportunidades correctas me encuentran en el momento correcto.'),
('Negocios y Clientes', 'Lidero mi emprendimiento con confianza y claridad.'),
('Gratitud', 'Estoy profundamente agradecido(a) por todo lo bueno en mi vida.'),
('Gratitud', 'La gratitud abre las puertas a más bendiciones en mi vida.'),
('Gratitud', 'Estoy en paz y agradecido(a) por el momento presente.'),
('Gratitud', 'Agradezco incluso los desafíos, ya que me hacen más fuerte.'),
('Gratitud', 'La gratitud transforma mi perspectiva y eleva mi energía.'),
('Gratitud', 'Agradecer hoy es sembrar para mañana.'),
('Gratitud', 'Veo bendiciones donde antes solo veía rutina.'),
('Gratitud', 'Mi gratitud crece cada vez que la practico.'),
('Gratitud', 'Encuentro motivos para agradecer incluso en lo pequeño.'),
('Gratitud', 'Agradezco quién fui, quién soy y quién estoy llegando a ser.'),
('Gratitud', 'Cada día tiene al menos un regalo escondido.'),
('Gratitud', 'Vivo agradecida por lo que tengo y abierta a lo que viene.'),
('Paz Mental', 'Estoy en paz con mi pasado, presente y futuro.'),
('Paz Mental', 'Mi mente está tranquila y mi corazón está en armonía.'),
('Paz Mental', 'Estoy rodeado(a) de tranquilidad y equilibrio.'),
('Paz Mental', 'Respiro profundamente y siento la serenidad llenarme.'),
('Paz Mental', 'La paz fluye a través de mí, como un río suave y constante.'),
('Paz Mental', 'Suelto lo que no puedo controlar.'),
('Paz Mental', 'Mi calma es más fuerte que cualquier caos externo.'),
('Paz Mental', 'Me doy permiso para descansar sin culpa.'),
('Paz Mental', 'Elijo pensamientos que me sostienen, no que me agotan.'),
('Paz Mental', 'Mi mente es un lugar seguro al que puedo volver.'),
('Paz Mental', 'No necesito tener todas las respuestas hoy.'),
('Paz Mental', 'Encuentro quietud en medio del movimiento.');
